"""chnage table name 

Revision ID: 88991251db3e
Revises: 
Create Date: 2022-03-05 17:21:47.795880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88991251db3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('User_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User_table',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_table_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='User_table_pkey')
    )
    op.drop_table('usertable')
    # ### end Alembic commands ###
