"""delete a table 

Revision ID: 96188de1e7a8
Revises: cba032f95d71
Create Date: 2022-03-05 17:31:36.949338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96188de1e7a8'
down_revision = 'cba032f95d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usertable2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usertable2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usertable2_pkey')
    )
    # ### end Alembic commands ###
